<a href="https://colab.research.google.com/github/EngineeredForHU/Machine-Learning-Reference/blob/main/PythonDataAnalysis/NumPyBasic(Ch4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 4: NumPy Basics – Arrays and Vectorized Computation

In this chapter, we will explore the **core features of NumPy**, the foundational library for numerical and scientific computing in Python.  
We will cover:
- ndarray, an efficient multidimensional array providing fast array-oriented

- arithmetic operations and flexible broadcasting capabilities


- Mathematical functions for fast operations on entire arrays of data without having to write loops

- Tools for reading/writing array data to disk and working with memory-mapped files

- Linear algebra, random number generation, and Fourier transform capabilities

- A C API for connecting NumPy with libraries written in C, C++, or FORTRAN

By the end of this section, you’ll understand how to use NumPy arrays as the backbone of data analysis, paving the way for more advanced numerical techniques and machine learning workflows.

For most data analysis applications, the main areas of functionality I’ll focus on are:

- Fast array-based operations for data munging and cleaning, subsetting and filtering, transformation, and any other kind of computation

- Common array algorithms like sorting, unique, and set operations

- Efficient descriptive statistics and aggregating/summarizing data

- Data alignment and relational data manipulations for merging and joining heterogeneous datasets

- Expressing conditional logic as array expressions instead of loops with if-elif-else branches

- Group-wise data manipulations (aggregation, transformation, and function application)

## Introduction to Numpy
One of the reasons NumPy is so important for numerical computations in python is because it is designed for efficiency on large arrays of data.

It provides efficient multi-dimensional array objects and various mathematical functions.

## Creating an array (ndarray)
**ndarray = N-dimentional arrays**

The easiest way to create an array is to use the **array function**. This accepts any sequence-like object(including other arrays) and produces a NumPy array containing the passed data.

**Note:** although **ndarrays** supports only `homogeneous` data types (elements within it are of the same data type).
- You can also use **ndarrays** with different data type, using dtype = 'object'

In [25]:
import numpy as np
# Here I will create a few different dimentional arrays

# creating a 1D array
arr_1d = np.array([1,2,3])

# creating a 2D array
arr_2d = np.array([[1,2,3],[3,4,6]])

# creating a 3D array
# A 3D array is like having 2D array stacked
arr_3d = np.array([[[1, 2,0],
                    [3, 4,6]],

                    [[5, 6,9],
                     [7, 8,10]]])

print(f"1D array:\n{arr_1d}\n")
print(f"2D array:\n{arr_2d}\n")
print(f"3D array:\n{arr_3d}")



1D array:
[1 2 3]

2D array:
[[1 2 3]
 [3 4 6]]

3D array:
[[[ 1  2  0]
  [ 3  4  6]]

 [[ 5  6  9]
  [ 7  8 10]]]


### Index Slicing
Here we will discuss Index Slicing with arrays.

## Array attributes
Here I will be learning the basic of NumPy Array attributes before getting into ndarrays in NumPy.
- ndim
- shape
- size
- dtype

### ndim
The ndim attribute returns the number of array dimensions of an array.

In [14]:
import numpy as np

# Here we will create a 3 dimensional array and return it to validate it is a 3 dimensional array.
arr = ([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.ndim(arr))


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2


##4.1: The NumPy ndarray: A Multidimensional Array Object
One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.     

In [1]:
import numpy as np

In [5]:
names = np.array([["angel", "bob"], ["ariana", "briana"]])
print(names.shape)   # (2, 2)


(2, 2)


bob
